export { default as MainLayout } from './MainLayout';
export { default as LandingPage } from './LandingPage';
export { default as RegisterPage } from './RegisterPage';
export { default as LoginPage } from './LoginPage';
export { default as DashboardLayout } from './DashboardLayout';
export { default as AccountPage } from './dashboard/AccountPage';
export { default as ConfigurationPage } from './dashboard/ConfigurationPage';
export { default as EventPage } from './dashboard/EventPage';
export { default as NoticeAdminPage } from './dashboard/NoticeAdminPage'
export { default as NotificationPage } from './dashboard/NotificationPage';
export { default as OrganizationPage } from './dashboard/OrganizationPage';
export { default as ProfilePage } from './dashboard/ProfilePage';
export { default as ReportPage } from './dashboard/ReportPage';
export { default as ResourcePage } from './dashboard/ResourcePage';
export { default as WelcomePage } from './dashboard/WelcomePage';
export { default as ErrorPage } from './ErrorPage';